// client/src/components/FlipCard.vue
<script setup>
import styles from '../styles/page.module.css';

defineProps({
  className: { type: String, default: '' },
  style: { type: Object, default: () => ({}) },
});
</script>

<template>
  <div :class="[styles.flipCard, className]" :style="style">
    <div :class="styles.flipCardInner">
      <div :class="styles.flipCardFront">
        <slot name="front" />
      </div>
      <div :class="styles.flipCardBack">
        <slot name="back" />
      </div>
    </div>
  </div>
</template>

// app/FlipCard.tsx
'use client';

import React from 'react';
import styles from './page.module.css';

export default function FlipCard({ 
  front, 
  back, 
  className = '',
  style
}: { 
  front: React.ReactNode; 
  back: React.ReactNode; 
  className?: string;
  style?: React.CSSProperties;
}) {
  return (
    <div className={`${styles.flipCard} ${className}`} style={style}>
      <div className={styles.flipCardInner}>
        <div className={styles.flipCardFront}>
          {front}
        </div>
        <div className={styles.flipCardBack}>
          {back}
        </div>
      </div>
    </div>
  );
}
