// client/src/components/GlowCard.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue';
import styles from '../styles/page.module.css';

defineProps({
  className: { type: String, default: '' },
  innerClassName: { type: String, default: '' },
  style: { type: Object, default: () => ({}) },
});

const emit = defineEmits(['click']);

const el = ref(null);

function handleMouseMove(e) {
  if (!el.value) return;
  const rect = el.value.getBoundingClientRect();
  const x = e.clientX - rect.left;
  const y = e.clientY - rect.top;
  el.value.style.setProperty('--x', `${x}px`);
  el.value.style.setProperty('--y', `${y}px`);
}

onMounted(() => {
  window.addEventListener('mousemove', handleMouseMove);
});

onUnmounted(() => {
  window.removeEventListener('mousemove', handleMouseMove);
});
</script>

<template>
  <div ref="el" :class="[styles.glowCard, className]" :style="style" @click="emit('click')">
    <div :class="innerClassName || styles.glowCardInner">
      <slot />
    </div>
  </div>
</template>

// app/GlowCard.tsx
'use client';
import React from 'react';
import styles from './page.module.css';

export default function GlowCard({ children, className = '', innerClassName = '', style, onClick }: { children: React.ReactNode, className?: string, innerClassName?: string, style?: React.CSSProperties, onClick?: () => void }) {
  const ref = React.useRef<HTMLDivElement>(null);
  
  React.useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (!ref.current) return;
      const rect = ref.current.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;
      ref.current.style.setProperty('--x', `${x}px`);
      ref.current.style.setProperty('--y', `${y}px`);
    };

    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  }, []);

  return (
    <div 
      ref={ref}
      className={`${styles.glowCard} ${className}`}
      style={style}
      onClick={onClick}
    >
      <div className={innerClassName || styles.glowCardInner}>
        {children}
      </div>
    </div>
  );
}
