// client/src/components/MeteorCard.vue
<script setup>
import styles from '../styles/page.module.css';
import Meteors from './Meteors.vue';

defineProps({
  className: { type: String, default: '' },
  style: { type: Object, default: () => ({}) },
});
</script>

<template>
  <div :class="className" :style="{ position: 'relative', width: '100%', height: '100%', ...style }">
    <div :class="styles.meteorCardGlow" />
    <div :class="styles.meteorCardInner">
      <div style="position: relative; z-index: 10; display: flex; flex-direction: column; height: 100%">
        <slot />
      </div>
      <Meteors :number="15" />
    </div>
  </div>
</template>

// app/MeteorCard.tsx
import React from 'react';
import styles from './page.module.css';
import Meteors from './Meteors';

export default function MeteorCard({ children, className = '', style }: { children: React.ReactNode, className?: string, style?: React.CSSProperties }) {
  return (
    <div className={className} style={{ position: 'relative', width: '100%', height: '100%', ...style }}>
      <div className={styles.meteorCardGlow} />
      <div className={styles.meteorCardInner}>
        <div style={{ position: 'relative', zIndex: 10, display: 'flex', flexDirection: 'column', height: '100%' }}>
          {children}
        </div>
        <Meteors number={15} />
      </div>
    </div>
  );
}
