// client/src/components/NeonBorder.vue
<script setup>
import { computed } from 'vue';
import styles from '../styles/page.module.css';

const props = defineProps({
  className: { type: String, default: '' },
  borderRadius: { type: Number, default: 12 },
  style: { type: Object, default: () => ({}) },
});

const wrapperStyle = computed(() => ({
  ...props.style,
  '--neon-radius': `${props.borderRadius}px`,
}));
</script>

<template>
  <div :class="[styles.neonBorderCard, className]" :style="wrapperStyle">
    <div :class="styles.neonBorderGlow" />
    <div :class="styles.neonBorderInner">
      <slot />
    </div>
  </div>
</template>

// app/NeonBorder.tsx
'use client';

import React from 'react';
import styles from './page.module.css';

export default function NeonBorder({
  children,
  className = '',
  borderRadius = 12,
  style,
}: {
  children: React.ReactNode;
  className?: string;
  borderRadius?: number;
  style?: React.CSSProperties;
}) {
  return (
    <div 
      className={`${styles.neonBorderCard} ${className}`}
      style={{ ...style, '--neon-radius': `${borderRadius}px` } as React.CSSProperties}
    >
      <div className={styles.neonBorderGlow} />
      <div className={styles.neonBorderInner}>
        {children}
      </div>
    </div>
  );
}
